### ISSUE TITLE
Initial login does not work anymore

### ISSUE THREAD

**Issue by Leppunen** [aitoiaita/linux-jagex-launcher#2]
After cleaning my existing credentials and trying to login fresh, the login process redirects to a "Something went wrong" page, and the url has a error message saying that the redirect_uri does not match the registered URIs. Possibly something has changed recently from jagex's side.

**Comment by aitoiaita** [comment]
Took me a while to get to this, but should be fixed by [ddd0563](https://github.com/aitoiaita/linux-jagex-launcher/commit/ddd056377cfda66397a8f49e7f94c0cf264d07c9)
